version: '3.4'

x-logging:
  &default-logging
  options:
    max-size: '10m'
    max-file: '5'
  driver: json-file

services:
  netbox: &netbox
    build:
      context: .
      args:
        - BRANCH=${VERSION-master}
    image: netboxcommunity/netbox:${VERSION-latest}
    depends_on:
    - postgres
    - redis
    - netbox-worker
    env_file: .env
    logging: *default-logging
    volumes:
    - ./startup_scripts:/opt/netbox/startup_scripts:ro
    - ./initializers:/opt/netbox/initializers:ro
    - ./configuration:/etc/netbox/config:ro
    - ./reports:/etc/netbox/reports:ro
    - ./nginx:/etc/netbox-nginx/
    - ${BASE_PATH:-/data}/netbox-static-files:/opt/netbox/netbox/static
    - ${BASE_PATH:-/data}/netbox-media-files:/opt/netbox/netbox/media

  netbox-worker:
    <<: *netbox
    depends_on:
    - redis
    logging: *default-logging
    entrypoint:
    - python3
    - /opt/netbox/netbox/manage.py
    command:
    - rqworker

  nginx:
    command: nginx -c /etc/netbox-nginx/nginx.conf
    image: nginx:1.15-alpine
    logging: *default-logging
    depends_on:
    - netbox
    volumes:
    - ${BASE_PATH:-/data}/netbox-static-files:/opt/netbox/netbox/static:ro
    - ./nginx:/etc/netbox-nginx/:ro
    networks:
      - default
      - web
    labels:
      - traefik.enable=${TRAEFIK_ENABLE:-true}
      - traefik.http.routers.netbox.entrypoints=https
      - traefik.http.routers.netbox.tls.certresolver=${TRAEFIK_CERT_RESOLVER:-default}
      - traefik.http.routers.netbox.tls=true
      - traefik.http.routers.netbox.rule=${NETBOX_URL_CONFIG:-Host(`netbox.naturalis.nl`)}

  postgres:
    image: postgres:10.4-alpine
    env_file: .env
    logging: *default-logging
    volumes:
      - ${BASE_PATH:-/data}/postgres:/var/lib/postgresql/data

  redis:
    image: redis:4-alpine
    command:
    - sh
    - -c # this is to evaluate the $REDIS_PASSWORD from the env
    - redis-server --appendonly yes --requirepass $$REDIS_PASSWORD ## $$ because of docker-compose
    env_file: .env
    logging: *default-logging
    volumes:
      - ${BASE_PATH:-/data}/redis:/data

  traefik:
    image: traefik:2.0.1
    container_name: traefik
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 8081:8080
    networks:
      - default
      - web
    logging: *default-logging
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik:/etc/traefik

volumes:
  netbox-static-files:
    driver: local
  netbox-nginx-config:
    driver: local
  netbox-media-files:
    driver: local
  netbox-report-files:
    driver: local
  netbox-postgres-data:
    driver: local
  netbox-redis-data:
    driver: local

networks:
  web:
    external: true
